variables:
  PROJECT_NAME: "call-centre-admin-panel"
  PROJECT_COMPONENT: "ui"
  DOCKER_PROJECT_NAME: "betalab-callcentre-digitaltwin"

before_script:
  - export CI_MERGE_REQUEST_TARGET_BRANCH_NAME=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:=$CI_COMMIT_REF_NAME}

stages:
- build
- analyse
- package

build:
  image: node:16
  stage: build
  script:
  - npm config set always-auth true
  - npm config set //${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken ${CI_JOB_TOKEN}
  - npm config set //${CI_SERVER_HOST}/api/v4/projects/39726/packages/npm/:_authToken ${CI_JOB_TOKEN}
  - yarn install
  # - yarn test
  - CI=true yarn build
  artifacts:
    paths:
    - build/
    - coverage/
    expire_in: 1 week
  only:
  - unstable
  - master
  - release
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/

analyse:
  image: node:16
  stage: analyse
  script:
    - npm config set always-auth true
    - npm config set //${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken ${CI_JOB_TOKEN}
    - npm config set //${CI_SERVER_HOST}/api/v4/projects/39726/packages/npm/:_authToken ${CI_JOB_TOKEN}
    - cp configs/sonar/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME.properties ./sonar-project.properties
    - yarn install
    - yarn sonar
  only:
  - unstable
  - master
  - release

package:
  image: registry.docker.nat.bt.com/betalab-build-tools/bt-kaniko-build:latest
  stage: package
  script:
  - echo "{\"auths\":{\"https://registry.docker.nat.bt.com\":{\"username\":\"$DOCKER_REGISTRY_USER\",\"password\":\"$DOCKER_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --cache=false --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination=registry.docker.nat.bt.com/$DOCKER_PROJECT_NAME/$PROJECT_NAME-$PROJECT_COMPONENT-$CI_COMMIT_REF_NAME:$CI_COMMIT_TAG
  only:
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/
